[profile.default]
auto_detect_solc = true
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
fs_permissions = [{ access = 'read', path = './test/payload'}]
[fmt]